[package]
name = "vmware-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5"
quick-xml = { version = "0.37.1", features = ["async-tokio"] }
csv = "1.2"
anyhow = "1.0"
futures = "0.3"
path-clean = "1.0"
zip = "2.2.2"
tokio-retry = "0.3.0"
log = "0.4"
simplelog = "0.12"
sha2 = "0.10"
rayon = "1.5.1"
num_cpus = "1.13.0"