[verification]
#Default chunk_size = 262144 (256KB)
chunk_size = 262144

#Default max_concurrent_files = 10 (Use 1000 for high performance)
max_concurrent_files = 10

#Default max_concurrent_verifications = num_cpus * 4
max_concurrent_verifications = 128

[download]
#Default max_concurrent_downloads = 10 
max_concurrent_downloads = 10
#Default buffer_size 8388608 = 8MB
buffer_size = 8388608

[general]
#Default thread_sleep_ms = 0
thread_sleep_ms = 0
