# This is a basic workflow that is manually triggered

name: Manual Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'DSvC Build workflow'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    name: Release - ${{ matrix.os-name }}
    strategy:
      matrix:
        os-name: [FreeBSD-x86_64, Linux-x86_64, Linux-aarch64, Linux-riscv64, Windows-x86_64, macOS-x86_64]
        include:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-freebsd
            skip_tests: true

          - os-name: Linux-x86_64
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl

          - os-name: Linux-riscv64
            runs-on: ubuntu-20.04
            target: riscv64gc-unknown-linux-gnu

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.runs-on }}
    env:
      OPENSSL_STATIC: true
      OPENSSL_DIR: /usr
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config musl-tools libssl-dev
        shell: bash

      - name: Install macOS Dependencies
        if: runner.os == 'macOS'
        run: |
          brew install openssl@3
        shell: bash

      - name: Install Windows Dependencies
        if: runner.os == 'Windows'
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static
        shell: pwsh

      - name: Set OpenSSL Environment
        run: |
          echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
        shell: bash

      - name: Build Release
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ubi
          target: ${{ matrix.target }}
